if(NOT DEFINED CSV_FILE)
    message(FATAL_ERROR "CSV_FILE is required")
endif()

file(READ "${CSV_FILE}" CSV_CONTENT)
string(REPLACE "\n" ";" CSV_LINES "${CSV_CONTENT}")
list(LENGTH CSV_LINES LINE_COUNT)
if(LINE_COUNT LESS 2)
    message(FATAL_ERROR "CSV has no data rows")
endif()

math(EXPR LAST_INDEX "${LINE_COUNT} - 1")
foreach(INDEX RANGE 1 ${LAST_INDEX})
    list(GET CSV_LINES ${INDEX} LINE)
    if(LINE STREQUAL "")
        continue()
    endif()
    string(REPLACE "," ";" FIELDS "${LINE}")
    list(GET FIELDS 1 TIME_S)
    list(GET FIELDS 11 GPS_FIX_VALID)
    if(TIME_S LESS 0.03)
        if(NOT GPS_FIX_VALID STREQUAL "1")
            message(FATAL_ERROR "gps_fix_valid changed before condition time at ${TIME_S}")
        endif()
    else()
        if(NOT GPS_FIX_VALID STREQUAL "0")
            message(FATAL_ERROR "gps_fix_valid did not drop at/after condition time ${TIME_S}")
        endif()
    endif()
endforeach()
