if(NOT DEFINED CSV_FILE)
    message(FATAL_ERROR "CSV_FILE is required")
endif()

file(STRINGS "${CSV_FILE}" CSV_LINES)
list(LENGTH CSV_LINES LINE_COUNT)
if(LINE_COUNT LESS 2)
    message(FATAL_ERROR "CSV has no data rows: ${CSV_FILE}")
endif()

list(GET CSV_LINES 0 HEADER)
string(FIND "${HEADER}"
            "trim_active,trim_achieved,trim_failed,trim_iteration_count,trim_residual_norm"
            TRIM_COLUMNS
)
if(TRIM_COLUMNS EQUAL -1)
    message(FATAL_ERROR "trim status columns are missing")
endif()

set(ACHIEVED_FOUND 0)
set(FAILED_FOUND 0)
set(PRE_ACHIEVED_FOUND 0)
foreach(LINE IN LISTS CSV_LINES)
    if(LINE STREQUAL "" OR LINE STREQUAL HEADER)
        continue()
    endif()
    string(REPLACE "," ";" FIELDS "${LINE}")
    list(GET FIELDS 47 TRIM_ACTIVE)
    list(GET FIELDS 48 TRIM_ACHIEVED)
    list(GET FIELDS 49 TRIM_FAILED)
    if(TRIM_ACHIEVED STREQUAL "1")
        set(ACHIEVED_FOUND 1)
    else()
        set(PRE_ACHIEVED_FOUND 1)
    endif()
    if(TRIM_FAILED STREQUAL "1")
        set(FAILED_FOUND 1)
    endif()
endforeach()

if(NOT ACHIEVED_FOUND)
    message(FATAL_ERROR "trim_achieved never transitioned to 1")
endif()
if(FAILED_FOUND)
    message(FATAL_ERROR "trim_failed was set")
endif()
if(NOT PRE_ACHIEVED_FOUND)
    message(FATAL_ERROR "no pre-achievement trim rows were identifiable")
endif()
