if(NOT DEFINED EXPECTED_FILE)
    message(FATAL_ERROR "EXPECTED_FILE is required")
endif()
if(NOT DEFINED ACTUAL_FILE)
    message(FATAL_ERROR "ACTUAL_FILE is required")
endif()
if(NOT EXISTS "${EXPECTED_FILE}")
    message(FATAL_ERROR "expected file does not exist: ${EXPECTED_FILE}")
endif()
if(NOT EXISTS "${ACTUAL_FILE}")
    message(FATAL_ERROR "actual file does not exist: ${ACTUAL_FILE}")
endif()

file(READ "${EXPECTED_FILE}" EXPECTED_CONTENT HEX)
file(READ "${ACTUAL_FILE}" ACTUAL_CONTENT HEX)
if(NOT EXPECTED_CONTENT STREQUAL ACTUAL_CONTENT)
    message(FATAL_ERROR "files differ: ${EXPECTED_FILE} ${ACTUAL_FILE}")
endif()
