#!/usr/bin/env python3
"""Run sitl_runner and print summary metrics from the generated CSV."""

import argparse
import subprocess
import sys

from sitl_csv import all_numeric_values_are_finite, load_dict_rows, numeric_column
from sitl_runner_command import (
    add_sitl_runner_arguments,
    build_sitl_runner_command,
    validate_sitl_runner_args,
)


def parse_args():
    parser = argparse.ArgumentParser(description="Run Altair SITL and summarize the CSV output.")
    add_sitl_runner_arguments(parser)
    parser.add_argument(
        "--plot",
        action="append",
        choices=("velocities", "attitudes", "rates", "position", "ecef", "all"),
        help="generate static SITL plot(s) after a successful run",
    )
    parser.add_argument(
        "--plots-dir",
        default="plots/sitl",
        help="directory for static plots generated by --plot",
    )
    args = parser.parse_args()
    validate_sitl_runner_args(parser, args)
    if args.scenario != "cruise6dof" and args.plot:
        parser.error("--plot is only supported with --scenario cruise6dof")
    return args


def max_abs(rows, column):
    return max(abs(value) for value in numeric_column(rows, column))


def print_metric(name, value):
    if isinstance(value, float):
        print(f"{name}={value:.6f}")
    else:
        print(f"{name}={value}")


def summarize(rows, scenario, profile, output_path):
    time_s = numeric_column(rows, "time_s")
    modes = numeric_column(rows, "mode")
    airspeeds = numeric_column(rows, "airspeed_mps")
    altitudes = numeric_column(rows, "altitude_m")

    print_metric("scenario", scenario)
    print_metric("profile", profile)
    print_metric("output", output_path)
    print_metric("rows", len(rows))
    print_metric("start_time_s", time_s[0])
    print_metric("end_time_s", time_s[-1])
    print_metric("final_mode", int(modes[-1]))
    print_metric("final_airspeed_mps", airspeeds[-1])
    print_metric("min_airspeed_mps", min(airspeeds))
    print_metric("max_airspeed_mps", max(airspeeds))
    print_metric("final_altitude_m", altitudes[-1])
    print_metric("min_altitude_m", min(altitudes))
    print_metric("max_altitude_m", max(altitudes))
    print_metric("finite", str(all_numeric_values_are_finite(rows)).lower())

    columns = rows[0].keys()
    if "roll_rad" in columns:
        print_metric("max_abs_roll_rad", max_abs(rows, "roll_rad"))
    if "pitch_rad" in columns:
        print_metric("max_abs_pitch_rad", max_abs(rows, "pitch_rad"))
    if "motor" in columns:
        motors = numeric_column(rows, "motor")
        print_metric("min_motor", min(motors))
        print_metric("max_motor", max(motors))


def plot_after_run(csv_path, plot_names, plots_dir):
    if not plot_names:
        return
    from plot_sitl import expand_plots, import_pyplot, plot_selected

    rows = load_dict_rows(csv_path)
    pyplot = import_pyplot(False)
    for plot_name in expand_plots(plot_names):
        plot_selected(rows, pyplot, plot_name, plots_dir)
    print_metric("plots_dir", plots_dir)


def terminate(process):
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5.0)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def run_command(command):
    process = subprocess.Popen(command, text=True)
    try:
        return process.wait()
    except KeyboardInterrupt:
        terminate(process)
        return 130


def main():
    args = parse_args()
    command = build_sitl_runner_command(args)

    try:
        returncode = run_command(command)
        if returncode != 0:
            if returncode == 130:
                return 130
            raise subprocess.CalledProcessError(returncode, command)
        rows = load_dict_rows(args.output)
        summarize(rows, args.scenario, args.profile, args.output)
        plot_after_run(args.output, args.plot, args.plots_dir)
    except (OSError, RuntimeError, subprocess.CalledProcessError, ValueError) as exc:
        print(f"run_sitl.py: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
