#!/usr/bin/env python3
"""Run sitl_runner and print summary metrics from the generated CSV."""

import argparse
import pathlib
import subprocess
import sys

from sitl_csv import all_numeric_values_are_finite, load_dict_rows, numeric_column


def parse_args():
    parser = argparse.ArgumentParser(description="Run Altair SITL and summarize the CSV output.")
    parser.add_argument("--build-dir", default="build")
    parser.add_argument("--scenario", default="smoke", choices=("smoke", "cruise6dof"))
    parser.add_argument(
        "--profile",
        default="cruise",
        choices=("cruise", "takeoff", "turn", "descent", "failsafe", "mission"),
        help="command profile for cruise6dof",
    )
    parser.add_argument("--duration", type=float, default=5.0)
    parser.add_argument("--dt", type=float, default=0.01)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--output", default="sitl.csv")
    parser.add_argument("--initial", help="initial-condition file for cruise6dof")
    parser.add_argument("--case", help="sectioned SITL case file for cruise6dof")
    parser.add_argument("--conditions", help="per-step SITL condition file for cruise6dof")
    parser.add_argument(
        "--frame-mode", choices=("ned", "ecef"), default="ecef", help="6DOF truth frame"
    )
    parser.add_argument(
        "--realtime",
        action="store_true",
        help="pace the compiled runner so one simulated second takes one wall-clock second",
    )
    parser.add_argument(
        "--qgc",
        "--mavlink",
        dest="qgc",
        action="store_true",
        help="stream cruise6dof SITL telemetry over MAVLink UDP; implies --realtime",
    )
    parser.add_argument(
        "--qgc-host",
        "--mavlink-host",
        dest="qgc_host",
        default="127.0.0.1",
        help="MAVLink UDP IPv4 address",
    )
    parser.add_argument(
        "--qgc-port", "--mavlink-port", dest="qgc_port", default="14550", help="MAVLink UDP port"
    )
    parser.add_argument("--mavlink-system-id", type=int, default=1, help="MAVLink system id")
    parser.add_argument(
        "--mavlink-source-port",
        type=int,
        default=0,
        help="optional local UDP source port for MAVLink packets",
    )
    parser.add_argument(
        "--plot",
        action="append",
        choices=("velocities", "attitudes", "rates", "position", "ecef", "all"),
        help="generate static SITL plot(s) after a successful run",
    )
    parser.add_argument(
        "--plots-dir",
        default="plots/sitl",
        help="directory for static plots generated by --plot",
    )
    args = parser.parse_args()
    if args.scenario != "cruise6dof" and args.initial is not None:
        parser.error("--initial is only supported with --scenario cruise6dof")
    if args.scenario != "cruise6dof" and args.case is not None:
        parser.error("--case is only supported with --scenario cruise6dof")
    if args.scenario != "cruise6dof" and args.conditions is not None:
        parser.error("--conditions is only supported with --scenario cruise6dof")
    if args.scenario != "cruise6dof" and args.profile != "cruise":
        parser.error("--profile is only supported with --scenario cruise6dof")
    if args.scenario != "cruise6dof" and args.plot:
        parser.error("--plot is only supported with --scenario cruise6dof")
    if args.qgc and args.scenario != "cruise6dof":
        parser.error("--mavlink/--qgc is only supported with --scenario cruise6dof")
    if args.mavlink_system_id < 1 or args.mavlink_system_id > 255:
        parser.error("--mavlink-system-id must be in 1..255")
    if args.mavlink_source_port < 0 or args.mavlink_source_port > 65535:
        parser.error("--mavlink-source-port must be in 0..65535")
    return args


def max_abs(rows, column):
    return max(abs(value) for value in numeric_column(rows, column))


def print_metric(name, value):
    if isinstance(value, float):
        print(f"{name}={value:.6f}")
    else:
        print(f"{name}={value}")


def summarize(rows, scenario, profile, output_path):
    time_s = numeric_column(rows, "time_s")
    modes = numeric_column(rows, "mode")
    airspeeds = numeric_column(rows, "airspeed_mps")
    altitudes = numeric_column(rows, "altitude_m")

    print_metric("scenario", scenario)
    print_metric("profile", profile)
    print_metric("output", output_path)
    print_metric("rows", len(rows))
    print_metric("start_time_s", time_s[0])
    print_metric("end_time_s", time_s[-1])
    print_metric("final_mode", int(modes[-1]))
    print_metric("final_airspeed_mps", airspeeds[-1])
    print_metric("min_airspeed_mps", min(airspeeds))
    print_metric("max_airspeed_mps", max(airspeeds))
    print_metric("final_altitude_m", altitudes[-1])
    print_metric("min_altitude_m", min(altitudes))
    print_metric("max_altitude_m", max(altitudes))
    print_metric("finite", str(all_numeric_values_are_finite(rows)).lower())

    columns = rows[0].keys()
    if "roll_rad" in columns:
        print_metric("max_abs_roll_rad", max_abs(rows, "roll_rad"))
    if "pitch_rad" in columns:
        print_metric("max_abs_pitch_rad", max_abs(rows, "pitch_rad"))
    if "motor" in columns:
        motors = numeric_column(rows, "motor")
        print_metric("min_motor", min(motors))
        print_metric("max_motor", max(motors))


def plot_after_run(csv_path, plot_names, plots_dir):
    if not plot_names:
        return
    from plot_sitl import expand_plots, import_pyplot, plot_selected

    rows = load_dict_rows(csv_path)
    pyplot = import_pyplot(False)
    for plot_name in expand_plots(plot_names):
        plot_selected(rows, pyplot, plot_name, plots_dir)
    print_metric("plots_dir", plots_dir)


def main():
    args = parse_args()
    exe = pathlib.Path(args.build_dir) / "vehicle" / "sitl_runner"
    command = [
        str(exe),
        "--scenario",
        args.scenario,
        "--profile",
        args.profile,
        "--duration",
        str(args.duration),
        "--dt",
        str(args.dt),
        "--seed",
        str(args.seed),
        "--output",
        args.output,
        "--frame-mode",
        args.frame_mode,
    ]
    if args.initial is not None:
        command.extend(["--initial", args.initial])
    if args.case is not None:
        command.extend(["--case", args.case])
    if args.conditions is not None:
        command.extend(["--conditions", args.conditions])
    if args.realtime:
        command.append("--realtime")
    if args.qgc:
        command.extend(
            [
                "--mavlink",
                "--mavlink-host",
                args.qgc_host,
                "--mavlink-port",
                args.qgc_port,
                "--mavlink-system-id",
                str(args.mavlink_system_id),
            ]
        )
        if args.mavlink_source_port:
            command.extend(["--mavlink-source-port", str(args.mavlink_source_port)])

    try:
        subprocess.run(command, check=True, text=True)
        rows = load_dict_rows(args.output)
        summarize(rows, args.scenario, args.profile, args.output)
        plot_after_run(args.output, args.plot, args.plots_dir)
    except (OSError, RuntimeError, subprocess.CalledProcessError, ValueError) as exc:
        print(f"run_sitl.py: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
