add_executable(test_fsw_boundaries test_fsw_boundaries.c)
target_link_libraries(test_fsw_boundaries PRIVATE altair_vehicle bayek_common)
altair_enable_warnings(test_fsw_boundaries)
add_test(NAME unit_fsw_boundaries COMMAND test_fsw_boundaries)

add_executable(test_mixer test_mixer.c)
target_link_libraries(test_mixer PRIVATE altair_vehicle bayek_common)
altair_enable_warnings(test_mixer)
add_test(NAME unit_mixer COMMAND test_mixer)

add_executable(test_altair_vehicle_interface test_altair_vehicle_interface.c)
target_link_libraries(test_altair_vehicle_interface PRIVATE altair_vehicle bayek_common)
altair_enable_warnings(test_altair_vehicle_interface)
add_test(NAME unit_altair_vehicle_interface COMMAND test_altair_vehicle_interface)

add_executable(test_altair_params test_altair_params.c)
target_link_libraries(test_altair_params PRIVATE altair_vehicle bayek_common)
altair_enable_warnings(test_altair_params)
add_test(NAME unit_altair_params COMMAND test_altair_params)

add_executable(test_altair_sim_model test_altair_sim_model.c)
target_link_libraries(test_altair_sim_model PRIVATE altair_sim_model bayek_common)
altair_enable_warnings(test_altair_sim_model)
add_test(NAME unit_altair_sim_model COMMAND test_altair_sim_model)

add_executable(test_altair_sim_params test_altair_sim_params.c)
target_link_libraries(test_altair_sim_params PRIVATE altair_sim_model bayek_common)
altair_enable_warnings(test_altair_sim_params)
add_test(NAME unit_altair_sim_params COMMAND test_altair_sim_params)

add_executable(test_sitl_initial_conditions test_sitl_initial_conditions.c)
target_link_libraries(test_sitl_initial_conditions PRIVATE altair_sitl bayek_common)
altair_enable_warnings(test_sitl_initial_conditions)
add_test(NAME unit_sitl_initial_conditions COMMAND test_sitl_initial_conditions)

add_executable(test_sitl_case test_sitl_case.c)
target_link_libraries(test_sitl_case PRIVATE altair_sitl bayek_common bayek_sim)
altair_enable_warnings(test_sitl_case)
add_test(NAME unit_sitl_case COMMAND test_sitl_case)

add_executable(test_sitl_conditions test_sitl_conditions.c)
target_link_libraries(test_sitl_conditions PRIVATE altair_sitl bayek_common bayek_sim)
altair_enable_warnings(test_sitl_conditions)
add_test(NAME unit_sitl_conditions COMMAND test_sitl_conditions)

add_executable(test_sitl_trim test_sitl_trim.c)
target_link_libraries(test_sitl_trim PRIVATE altair_sitl bayek_common bayek_sim)
altair_enable_warnings(test_sitl_trim)
add_test(NAME unit_sitl_trim COMMAND test_sitl_trim)
