add_executable(test_math test_math.c)
target_link_libraries(test_math PRIVATE bayek_common)
altair_enable_warnings(test_math)
add_test(NAME unit_math COMMAND test_math)

add_executable(test_control test_control.c)
target_link_libraries(test_control PRIVATE bayek_common)
altair_enable_warnings(test_control)
add_test(NAME unit_control COMMAND test_control)

add_executable(test_mission test_mission.c)
target_link_libraries(test_mission PRIVATE bayek_fsw bayek_common)
altair_enable_warnings(test_mission)
add_test(NAME unit_mission COMMAND test_mission)

add_executable(test_mixer test_mixer.c)
target_link_libraries(test_mixer PRIVATE altair_vehicle bayek_common)
altair_enable_warnings(test_mixer)
add_test(NAME unit_mixer COMMAND test_mixer)

add_executable(test_sim6dof test_sim6dof.c)
target_link_libraries(test_sim6dof PRIVATE bayek_sim bayek_common)
altair_enable_warnings(test_sim6dof)
add_test(NAME unit_sim6dof COMMAND test_sim6dof)

add_executable(test_sim_fixedwing test_sim_fixedwing.c)
target_link_libraries(test_sim_fixedwing PRIVATE bayek_sim bayek_common)
altair_enable_warnings(test_sim_fixedwing)
add_test(NAME unit_sim_fixedwing COMMAND test_sim_fixedwing)

add_executable(test_altair_sim_model test_altair_sim_model.c)
target_link_libraries(test_altair_sim_model PRIVATE altair_sim_model bayek_common)
altair_enable_warnings(test_altair_sim_model)
add_test(NAME unit_altair_sim_model COMMAND test_altair_sim_model)

add_executable(test_sitl_initial_conditions test_sitl_initial_conditions.c)
target_link_libraries(test_sitl_initial_conditions PRIVATE altair_sitl bayek_common)
altair_enable_warnings(test_sitl_initial_conditions)
add_test(NAME unit_sitl_initial_conditions COMMAND test_sitl_initial_conditions)
