[env:arduino_altair]
platform = atmelavr
board = uno
framework = arduino
build_flags =
  -I../../framework/common
  -I../../framework/fsw
  -I../../vehicles/altair
  -Ilib/altair_hal
build_src_filter =
  +<*>
  +<../../framework/common/*.c>
  +<../../framework/fsw/*.c>
  +<../../vehicles/altair/*.c>
