[env:arduino_altair]
platform = atmelavr
board = uno
framework = arduino
build_flags =
  -I../../bayek/common
  -I../../bayek/fsw
  -I../../params
  -I../../mixer
  -I../../config
  -I../../vehicle
  -Ilib/altair_hal
build_src_filter =
  +<*>
  +<../../bayek/common/*.c>
  +<../../bayek/fsw/*.c>
  +<../../params/*.c>
  +<../../mixer/*.c>
  +<../../vehicle/altair_vehicle.c>
